stages:
  - build
  - build_pypi_package
  - test
  - deploy

build_and_publish_template:
  stage: build_pypi_package
  image: python:3.8
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
  before_script:
    - apt-get update --yes
    - apt-get install -y build-essential gcc clang clang-tools cmake libboost-all-dev
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install twine 
    - ls
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }} TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }} python -m twine upload --skip-existing --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 days

linux:build:
  stage: build
  tags: 
    - linux
  image: ubuntu:20.04
  before_script:
    - apt-get update --yes
    - DEBIAN_FRONTEND="noninteractive" apt-get install --yes
        build-essential 
        cmake
        libboost-all-dev
  script:
    - echo "Starting build..."
    - mkdir _build && cd _build
    - cmake ..
    - cmake --build . --target install
  artifacts:
    paths:
      - _build


docs:test:
  stage: test
  image: python:3.7-alpine
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - "echo Building docs for test..."
  - pip install -U sphinx
  - pip3 install sphinx-rtd-theme
  - pip3 install breathe
  - pip3 install sphinx-sitemap
  - cd docs_sphinx
  - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

docs:pages:
  stage: deploy
  image: python:3.7-alpine
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - "echo Deploying docs..."
  - pip install -U sphinx
  - pip3 install sphinx-rtd-theme
  - pip3 install breathe
  - pip3 install sphinx-sitemap
  - cd docs_sphinx
  - sphinx-build -b html . public
  - cd ..
  - mkdir public
  - mv docs_sphinx/public/* public
  artifacts:
    paths:
    - public
  only:
  - master
