stages:
  - build
  - test
  - deploy


linux:build:
  stage: build
  tags: 
    - linux
  image: ubuntu:20.04
  before_script:
    - apt-get update --yes
    - DEBIAN_FRONTEND="noninteractive" apt-get install --yes
        build-essential 
        cmake
        libboost-all-dev
  script:
    - echo "Starting build..."
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build


docs:test:
  stage: test
  image: python:3.7-alpine
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - "echo Building docs for test..."
  - pip install -U sphinx
  - pip3 install sphinx-rtd-theme
  - pip3 install breathe
  - pip3 install sphinx-sitemap
  - cd docs_sphinx
  - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

docs:pages:
  stage: deploy
  image: python:3.7-alpine
  before_script:
  - apk update
  - apk add doxygen
  - apk add ttf-freefont graphviz
  script:
  - "echo Deploying docs..."
  - pip install -U sphinx
  - pip3 install sphinx-rtd-theme
  - pip3 install breathe
  - pip3 install sphinx-sitemap
  - cd docs_sphinx
  - sphinx-build -b html . public
  - cd ..
  - mkdir public
  - mv docs_sphinx/public/* public
  artifacts:
    paths:
    - public
  only:
  - master
