name: python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
   runs-on: ${{ matrix.os }}
   strategy:
      matrix:
        os: [ubuntu-20.04]
   steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install Cmake
      run: >-
        sudo apt-get install build-essential cmake
    - name: Pip Install Package
      working-directory: ${{github.workspace}}
      run: python3.11 -m pip install .
  
    - name: Test package
      working-directory: ${{github.workspace}}
      run: |
        python3.11 -m pip install pytest
        python3.11 -m pytest ./tests/pybind_test.py 
      
